### ISSUE TITLE
Upload CSV functionality

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/simpleassettracker#8]
Suggested user flow : 

- [x] User goes to upload page by clicking on a button
- [x] They see the instructions and a link to download the template CSV file
- [x] User can see where to upload a completed file
- [x] We check the format of the file? (is this possible?)
- [x] We display the assets on the users own asset page
- [x] The user assets are saved
