### ISSUE TITLE
Asset properties (laptops)

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/simpleassettracker#97]
Properties we track for laptops : 

- [x] Makers Asset Tag (starts with MA)

- [x] Status (drop down with options : In Repair, Locked at the office, On Loan, Ready, Needs Resetting, Extended Loan, Unknown, Lost, Stolen, Unavailable)

- [x] Serial Number (must be unique)

- [x] Condition

- [x] Spec : Screen size, hard drive, ram, year, type (Pro, Air, Macbook)

- [ ] Loaned to? (linked to the Equipment Loan tracking work)

- [ ] Each laptop is also either on a lease or owned by Makers. If on a lease ideally we should be able to see the lease information somewhere (perhaps under Leases?)
